site_name: Cognition and Learning Lab

copyright: Copyright &copy; 2020 Cognition and Learning Laboratory

theme: 
  name: material
  palette: 
    primary: black
  # logo: img/lightbulb-3.png
  logo: 
    icon: book

extra_css:
- css/extra.css

markdown_extensions:
  - attr_list

# repo_url: 'https://github.com/PCLLAB/handbook'
# repo_name: 'PCLLAB/handbook'

docs_dir: docs
# site_dir: labdocs

nav:
- Home: index.md
- People: people.md
- Projects: projects.md
- Publications: publications.md
- News: news.md
- Join Us: joinus.md
