site_name: My Docs
site_url: https://example.com/
copyright: Copyright &copy; 2021 Cognition and Learning Laboratory

theme:
  name: material
  palette:
    primary: black
    accent: amber
  custom_dir: overrides

extra_css:
  - css/baseline.css
  - css/people.css

markdown_extensions:
    - attr_list
    - pymdownx.extra
    - meta # Add frontmatter + allows hiding sidebars
    