site_name: Cognition and Learning Lab

copyright: Copyright &copy; 2020 Cognition and Learning Laboratory

theme:
    name: material
    palette:
        primary: black
        secondary: amber
    # logo: img/lightbulb-3.png
    favicon: img/favicon.ico
    logo: "img/lightbulb-nav-logo.png"
    custom_dir: "theme/"
    feature:
        tabs: false

extra_css:
    - css/extra.css
    - css/modal.css
    - css/people.css
    - css/grid.css
    - css/critical.min.css
    - css/navbar.css

extra_javascript:
    - js/headerfix.js
    - js/jquery-3.4.1.min.js
    - js/deferred.min.js

markdown_extensions:
    - attr_list
    - pymdownx.extra

# repo_url: 'https://github.com/PCLLAB/handbook'
# repo_name: 'PCLLAB/handbook'

docs_dir: docs
# site_dir: labdocs

nav:
    - Home: index.md
    - People:
          - People: people.md
    - Projects:
          - Projects: projects.md
    - Publications:
          - Publications: publications.md
    - News:
          - News: news.md
    - Join Us:
          - Join Us: joinus.md

plugins: []
