site_name: Cognition and Learning Lab
site_url: https://learninglab.psych.purdue.edu/
repo_url: https://github.com/PCLLAB/pcllab.github.io
copyright: Copyright &copy; 2024 Cognition and Learning Laboratory

theme:
  name: material
  palette:
    primary: black
    accent: amber
  custom_dir: overrides
  favicon: img/favicon.ico

extra_css:
  - css/baseline.css
  - css/people.css
  - css/header.css
  - css/footer.css
  - css/sidebars.css
extra_javascript:
  - js/header.js

markdown_extensions:
  - mdx_truly_sane_lists
  - attr_list
  - pymdownx.extra
  - pymdownx.keys
  - meta # Add frontmatter + allows hiding sidebars
  # For admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # For super cool codeblocks
  - pymdownx.highlight:
      # use_pygments: true #doesn't seem to make a difference
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
  # Content tabs
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - macros
# extra:
#   handbookPage: /handbook/
nav:
  # - Home: index.md
  - People: people.md
  - Projects: projects.md
  - Publications: publications.md
  # - News: news.md
  - Join Us: joinus.md

  - Handbook:
      - Introduction:
          - Home: handbook/index.md
          - Getting on Board: handbook/introduction/getting-on-board.md
          - Links: handbook/introduction/links.md
          - Purpose: handbook/introduction/purpose.md
          - Funding: handbook/introduction/funding.md
          - People and Roles: handbook/introduction/people.md
          - Overview of the Research Process: handbook/introduction/research-process.md
      - Lab Policies:
          - Code of Conduct: handbook/lab-policies/lab-policies.md
          - Rules: handbook/lab-policies/lab-rules.md
          - Rooms: handbook/lab-policies/lab-rooms.md
          - Computers: handbook/lab-policies/lab-computers.md
          - Paper and Digital Files: handbook/lab-policies/handling-files.md
          - Supplies: handbook/lab-policies/supplies.md
          - Keys and Security: handbook/lab-policies/keys-and-security.md
          - Keeping the Lab Clean: handbook/lab-policies/lab-procedures.md
      - Running Lab Experiments:
          - IRB Information: handbook/lab-experiments/lab-irb-information.md
          - Preparing a Lab Experiment: handbook/lab-experiments/preparing-lab-experiment.md
          - Starting a New Sona Experiment: handbook/lab-experiments/new-sona.md
          - Working in Sona: handbook/lab-experiments/working-in-sona.md
          - Checklist for Running Lab Experiments: handbook/lab-experiments/checklist.md
          - Awarding Credits in Sona: handbook/lab-experiments/awarding-credits.md
          - Scanning and Archiving: handbook/lab-experiments/scanning.md
      - Running Online Experiments:
          # - Web Programming: handbook/web-experiments/index.md
          # - Getting Started: handbook/programming-guide/programs.md
          # - Repositories: handbook/web-experiments/repositories.md
          # - Common Tasks: handbook/web-experiments/common-tasks.md
          - Testing Experiments: handbook/web-experiments/testing-experiments.md
          # - Troubleshooting and Common Errors: handbook/web-experiments/troubleshooting-and-common-errors.md
          - Making Experiments Live: handbook/web-experiments/making-experiments-live.md
          - Online Sona Experiments: handbook/web-experiments/running-experiments.md
          # - General Tips: handbook/web-experiments/general-tips.md
          - MTurk: handbook/web-experiments/mturk.md
          # - MTurk Calculator: handbook/web-experiments/mturk-calculator.md
      - Lab Connections and Servers:
          - Set up a VPN: handbook/connections-servers/VPN.md
          # - Learning Lab Box: handbook/connections-servers/learninglab-shared.md
          - Jarvis: handbook/connections-servers/jarvis.md
      - Web Programming Guide:
          - Necessary Programs: handbook/programming-guide/programs.md
          - Repositories: handbook/programming-guide/repositories.md
          - File Types: handbook/programming-guide/file-types.md
          - Getting Started w/ jsPsych7: handbook/programming-guide/getting-started-jspsych-7.md
          - Convering plugin to jsPsych7: handbook/programming-guide/converting-plugins.md
          - Basic Experiment Structure: handbook/programming-guide/basic-experiment-structure.md
            - Versions and Counterbalences: handbook/programming-guide/counterbalence.md
            - Starting Experiments: handbook/programming-guide/starting.md
            - Materials: handbook/programming-guide/materials.md
            - Timeline: handbook/programming-guide/timeline.md
            - Present Stimuli: handbook/programming-guide/study-list.md
            - Distractor Tasks: handbook/programming-guide/distractor.md
            - Free Recall: handbook/programming-guide/free-recall.md
            - Cued Recall: handbook/programming-guide/cued-recall.md
            - Saving Data: handbook/programming-guide/saving-data.md
            - Unsorted Examples: handbook/programming-guide/unsorted-examples.md
          - Essentials: handbook/programming-guide/essentials.md
          - Plugins: handbook/programming-guide/plugins.md
      - Resources:
          - Who's Who in the Psych Department: handbook/resources/whos-who.md
          - Recommendation Letters: handbook/resources/letters.md
          # File does not exist
          # - Graduate and Postdoctoral Training: resources/training.md
          # - Job Search: handbook/resources/jobs.md
          - Travel Information: handbook/resources/travel.md
          - Journals: handbook/resources/journals.md
      - Misc:
          - handbook/misc/mkdocs-customizations.md
          - handbook/misc/plugin-development.md
          - handbook/misc/server.md
